### ISSUE TITLE
draft content contributors credited on parent

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#12]
I have found at least one case in which a location has been added to an existing place by a user and left in drafting state, but that user's name incorrectly appears in the "contributors" list for the parent place. On the credits page, the user (incorrectly) gets contributor credit for the affected place, but (correctly) not for the location, which is still in drafting. I see no evidence in the edit history for the place that the user in question should have been given contributor credit manually on the place.
Steps to reproduce:
Visit http://pleiades.stoa.org/places/246204/ and note that David Díez Mata appears in the contributors' list. He is the creator of the subordinate (drafting state) location http://pleiades.stoa.org/places/246204/atxa but seems not to have made any changes to the place itself. Visit http://pleiades.stoa.org/credits and search in page for "Mata". Note that he is credited with "one other contribution", which points to http://pleiades.stoa.org/places/246204/.

Migrated from http://pleiades.stoa.org/docs/site-issue-tracker/55

**Comment by paregorios** [comment]
Possibly related to #7 and/or #37

**Comment by paregorios** [comment]
Verified.

**Comment by paregorios** [comment]
NB: we should also make sure that creators and contributors on "pending" content are not credited on published content.

**Comment by cguardia** [comment]
For places, contributors include creators and contributors of contained names and locations, which is why David Diez Mata is included. Do you want this behavior to be removed entirely or only changed to not include creators and contributors of unpublished subitems?

**Comment by davisagli** [comment]
We do want the creators and contributors from published subitems.

**Comment by paregorios** [comment]
The only thing that needs to change is rejecting strings from unpublished
subordinate items.

## 

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by cguardia** [comment]
I pushed in a change for rejecting contributors from unpublished subitems, but there are two problems with the other code as it is right now:
1. Once the name is in the main object contributors field, it will remain there, even if the review state of subitems changes. We would need to change the event to always review subobjects and take out any names that come from unpublished ones. However, that might result in removing a manually added name.
2. Since setting contributors happens in the modified event, we would need to modify all places to get the new behavior in.

**Comment by paregorios** [comment]
@cguardia I understand your item 1 and I am happy with that remaining an exception. The editors will have to manually remove contributors from the parent place if we retract something.

I don't extactly understand your item 2. Do you mean that _if_ we made the changes necessary to change the behavior for item 1, then we'd have to do a massive migration, or do you mean that even the partial fix you've pushed requires a massive migration?

**Comment by cguardia** [comment]
Yes, a script of some sort would be required, because contributors are not calculated at display time. They are set only when the object is edited or created. For example, to fix the example place above, David Díez Mata has to be manually removed from the list of contributors (because of comment 1 from myself above), then when that change is saved, my code change will make sure he is not added again.

**Comment by davisagli** [comment]
If I'm understanding Carlos correctly, he's saying that it's hard to fix this for existing content because we can't automatically determine which "extra" names are there because someone explicitly added them vs. because they came from unpublished subitems.

But we don't need a migration to fix it so that creators/contributors of future unpublished subitems won't show up on the Place until the subitem is published. Correct?

**Comment by cguardia** [comment]
Correct. Thanks for the explanation.

**Comment by paregorios** [comment]
I am good with a code change that only prevents grabbing creators and contributors from unpublished subordinate locations, names, etc. in the future. I understand that existing examples will be unchanged. In other words, what @cguardia has already done is fine with me. 

Please push to staging so I can check it out.

**Comment by cguardia** [comment]
This is on staging already.

**Comment by paregorios** [comment]
@cguardia can you point me to the code for this? I'm not understanding the logic.

**Comment by cguardia** [comment]
For place subitems, I added a check for the review_state, to only add the subitem's contributor when the subitem is already published:

https://github.com/isawnyu/PleiadesEntity/blob/c34cb573338f9226d491b3a10ddb3561e886f53d/Products/PleiadesEntity/event.py#L87

**Comment by cguardia** [comment]
Oh, and it's important to remember that the value is changed only when the place itself is edited, so publishing a subitem will not automatically update contributors. This last thing might be something we could change later on.

**Comment by davisagli** [comment]
@cguardia I think now is the right time to change that. It should be as simple as subscribing `contributorsSubscriber` to the workflow transition event in addition to IObjectModifiedEvent

**Comment by paregorios** [comment]
yes please

**Comment by cguardia** [comment]
It was true that this was an easy fix. It's on staging now.

**Comment by paregorios** [comment]
This works great! Please deploy to production.

**Comment by cguardia** [comment]
Deployed.
