### ISSUE TITLE
upgrade Pelagios Portlet to use newer API

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#124]
Via @rsimon [Our Pelagios portlet](https://github.com/isawnyu/pleiades.portlet.pelagios) uses a deprecated version of the Pelagios API (now re-branded as the Peripleo API). Current docs are here: https://github.com/pelagios/peripleo#peripleo-1

**Comment by rsimon** [comment]
Hi Tom! 

I took a quick look at [client.py](https://github.com/isawnyu/pleiades.portlet.pelagios/blob/master/pleiades/portlet/pelagios/client.py), which is where you'd need to make the adjustments if I understood that right?

If you query `http://pelagios.org/peripleo/places/{escaped Pleiades URI}` instead of the old `http://pelagios.dme.ait.ac.at/api/places/{escaped Pleiades URI}/datasets.json` you should be getting pretty much the same data (and more! :-). [JSON example here.](http://pelagios.org/peripleo/places/http:%2F%2Fpleiades.stoa.org%2Fplaces%2F423025?prettyprint=true)

From the JSON, grab the `referenced_in` field. For each dataset in that list, you'll get the `count` and `title` - same as in the old API. The URI you can construct from the `identfier` field. Assuming you want to link to our Peripleo UI (rather than do another API call), with a search pre-set for your current place, and limited to that specific dataset, the URL would be:

`http://pelagios.org/peripleo/map#places={escaped Pleiades URI}&datasets={identifier}&f=open

[Example link](http://pelagios.org/peripleo/map#places=http%3A%2F%2Fpleiades.stoa.org%2Fplaces%2F423025&datasets=bacf05728143af944e671120959bcc1ee8869e1e010a7371e3268a9e9d2be358&f=open)

(Note: the `f=open` just causes the filterpanel to open, so that there's at least a small visual hint that the search is limited to the dataset.)

**Comment by paregorios** [comment]
Thanks @rsimon! We'll try to get on this as soon as we rollout [the pending performance upgrade](https://github.com/isawnyu/pleiades-gazetteer/milestones?direction=asc&sort=due_date&state=open).

**Comment by alecpm** [comment]
This is now live on the EC2 staging server, see e.g.:

http://52.38.6.139/places/579885

I've implemented a 10 minute (maximum) RAM cache for the API request results, let me know if you'd like to shorten or lengthen that cache timeout.

**Comment by paregorios** [comment]
I think the 10 minute caching target is a good place to start. @rsimon do you have any guidelines for how long third parties should be caching results?

**Comment by rsimon** [comment]
I don't think we'd update even the most dynamic sources more than once a week. So almost any caching interval will definitely be safe.

**Comment by alecpm** [comment]
@paregorios given that, let me know if you want to bump it up to something a bit more generous (e.g 24 hours). The benefit of a longer cache time for this is likely to be small, but if the data is infrequently updated it may be worth doing anyway.

**Comment by paregorios** [comment]
Let's make it 24 and then see how it behaves on the live site. Apart from
our performance, I don't want to pummel the Peripleo api server more than
necessary. Thanks.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by alecpm** [comment]
Done and merged to master so this should go live along with the optimizations.
