### ISSUE TITLE
content actions menus disappearing after editing

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#135]
Steps to reproduce:

- Navigate to a place page (in any state)
- Edit the content item (one must have permissions to do so)
- Save
- The browser reloads with the place + ```/base_view``` in which the "content actions" menus are missing.

Screen shot showing place page before editing (content actions are visible):

<img width="967" alt="before" src="https://cloud.githubusercontent.com/assets/263285/15344416/b23cd928-1c74-11e6-8eb9-fa3dfc1fb64e.png">

Screen shot showing place page "base view" that comes back after saving the edit (content actions are gone):

<img width="917" alt="after" src="https://cloud.githubusercontent.com/assets/263285/15344424/ca2bbedc-1c74-11e6-8977-a579e2d99194.png">

**Comment by davisagli** [comment]
This is probably because the actions menu only appears when looking at the item's default view, and the default view is now the content negotiation view that @alecpm added, which indirectly invokes base_view. Possible solutions:
1. Do content negotiation in an IPublishTraverse adapter, so that base_view is resolved as part of traversal and recognized as the default view.
2. Adjust the redirect from the edit form to make sure it doesn't append /base_view

**Comment by alecpm** [comment]
There will likely be some small but useful benefits to moving to an IPublishTraverse adapter, and though it might be slightly easier to modify the redirect, doing so would also be a bit more invasive (modifying Archetypes form actions). I'd recommend we go with 1.

**Comment by alecpm** [comment]
This is fixed (in a slightly different manner than expected) on staging.

**Comment by paregorios** [comment]
Confirmed on staging: we still end up on base view after an edit, but now the content actions menus are available and functional. Please deploy to production.

**Comment by alecpm** [comment]
Done.

**Comment by paregorios** [comment]
:)
