### ISSUE TITLE
"Member since" strings on credits page have no date values

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#136]
E.g.:

> Member since . 5 additions , 6 other contributions

http://pleiades.stoa.org/credits

**Comment by davisagli** [comment]
It determines this date from the creation date of the member folder, but was traversing to member folders in a way that they're not found when logged out. Fixed. I also fixed the formatting a bit (the extra spaces) and made it not show " since " for members that don't have a member folder, of which there are a few.
