### ISSUE TITLE
multiple places with 503 errors on production edit/checkout

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#145]
Another editor reported, and I have confirmed, that users with permissions to direct-edit or checkout published items are experiencing "503 backend fetch failed" errors on production, apparently beginning sometime yesterday afternoon and continuing this morning. Here are some examples:

attempted edit
http://pleiades.stoa.org/places/648548
Guru Meditation:
XID: 1769219
Varnish cache server 

attempted edit
http://pleiades.stoa.org/places/79651
Guru Meditation:
XID: 2297194
Varnish cache server

attempted checkout
http://pleiades.stoa.org/places/687931
Guru Meditation:
XID: 673848
Varnish cache server

**Comment by alecpm** [comment]
Right now all of these are currently working for direct edit on my end. A 503 error generally means that varnish timed out on a long running request. The edit form is one of the slower pages on the site according to our New Relic data (though it is inconsistently slow), but generally loads fast enough to avoid a timeout. We implemented some additional tracing in New Relic on that view yesterday in the hope of better understanding the performance issues. Unfortunately, ISAW's New Relic Pro trial has since expired, which means we no longer have access to that more automated detailed profile information. It might be a good idea to look into joining the [New Relic Non-Profit program](https://newrelic.com/nonprofit) to retain access to the Pro-level data.

I'm looking at a manually initiated thread profile now, but will also extend the Varnish and HAProxy timeouts so that a slow response doesn't so easily trigger a 503.

**Comment by paregorios** [comment]
I'll look into getting us pro on an on-going basis asap

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
I have submitted the non-profit new relic request.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
Were there any dumps (e.g., RDF) running during the period 5pm - 7am US EDT?

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
Site is now notably faster across all actions than it was a couple of hours ago.

**Comment by alecpm** [comment]
The pleiades RDF dump did complete it's run at 8:35 AM EDT today. It should have started at 6:47 AM according to the crontab. The daily json, kml and csv dumps should have started at 6:25 AM, and they completed at 9:21 AM EDT. It might be a good idea to have the daily and weekly jobs run non-concurrently. None of that explains what could have happened starting at 5:00 PM yesterday though. One thing @davisagli  noted is that the traffic to the site increased significantly after the robots.txt was changed to allow more crawling, it could be related to a higher baseline of traffic or an aggressive crawler or two running at an inopportune time.

**Comment by alecpm** [comment]
It's also worth noting that the newly working Flickr portlet is one of the slower elements of the site, and it renders on almost all pages. There could be some improvements made to better cache the API data from Flickr, but the benefits of that would be small since the request varies from Place to Place. Alternatively, we could try to refactor the portlet to make the API calls and render the data from the browser side.

**Comment by paregorios** [comment]
Yes, there was some discussion with @davisagli and @ryanfb I think on IRC
the other day about refactoring/replacing the Flickr portlet with a pure,
client-side Javascript solution. I will undertake to capture the content of
that conversation and get it into appropriate Github issue and/or Scrumdo
story.

It also occured to me this morning that we really don't need to be seeing
the Flickr portlet in the edit view, just in base view. Would it be a major
hassle to suppress it loading at all when we're editing?


-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
Yeah, we've seen in the P3 past that multiple bots visiting at the same
time can really clobber things. And recent changes to robots.txt, apache
conf, and google webmaster settings have removed most of the obstacles we
put in place to try to mitigate those effects (because we want the site to
register well in the search indexes).

Apache logs show only 19 503 errors since 0700 EDT yesterday. Most of them
were the google bot, but that's still a pretty small number if anything but
a transient was happening.  I'll try to do a little more log analysis to
see if there were heavy but mostly successful loads (or other error codes)
going on during this period.



-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
There are a large number of plain 500s being returned to the googlebot, bing, and possibly some other users during the last 24 hours (and this is ongoing). I will email an apache log extract with details to @alecpm

**Comment by alecpm** [comment]
OK, I've set some timeouts in the varnish configs to match/exceed those we already have set in our HAProxy config. That should allow these requests to get served to clients, rather than having the execute on the server and get hung up on by varnish. Might be best to open a new ticket with the 500 errors as an attachment.

Let me know how the New Relic non-profit application works out. I believe it's a fairly new offering, and we don't yet have any experience with it.

**Comment by paregorios** [comment]
Thanks will do.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by paregorios** [comment]
Google's Webmaster tools thinks we're making good progress on this front (see "Server Error" graph of 50x-series responses, below). Will close the general ticket and open new ones for specific problems.

![screen shot 2016-07-05 at 9 17 15 am](https://cloud.githubusercontent.com/assets/263285/16587666/5ba484ce-4291-11e6-8904-bd049b77bb74.png)
