### ISSUE TITLE
multiple 500 errors

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#146]
We are seeing a very large number of 500 errors in the logs on pleiades. Opening new ticket as suggested by @alecpm in #145.

**Comment by alecpm** [comment]
I just committed a fix for this. You can see the details of the issue here for the time being:

http://pleiades.stoa.org/prefs_error_log_showEntry?id=1464535315.890.495335704717

(you'll probably need a couple reloads to get the right ZEO Client). It's related to a couple issues in the new content negotiation setup. The first one is an long-standing issue where crawlers that pass in an ACCEPT header of '*/*' were treated as incompatible/invalid and sent to the custom 406 page. The second is a new issue introduced with the content negotiation fix deployed the other day caused that custom 406 error page to throw a 500 error. I've committed and pushed a fix for the latter issue, and will add a fix for the former one shortly.

**Comment by alecpm** [comment]
Both fixes are now deployed to production. Looking through the logs, I've noticed a couple additional unrelated errors and will make tickets for those.

**Comment by paregorios** [comment]
Thanks!
