### ISSUE TITLE
Place view string exception when calculating "neighborhood" box (?)

### ISSUE THREAD

**Issue by alecpm** [isawnyu/pleiades-gazetteer#148]
See e.g.:

http://pleiades.stoa.org/places/776211/

**Comment by alecpm** [comment]
A somewhat different traceback in the same code path:

http://pleiades.stoa.org/places/589764/

**Comment by paregorios** [comment]
Well spotted. There are other place examples wherein these errors are occurring.

**Comment by davisagli** [comment]
The first traceback is because there's a location (http://pleiades.stoa.org/places/776211/undetermined/edit) which references a CAP grid inset (http://atlantides.org/capgrids/79/inset) that does not exist in maps.csv in pleiades.capgrids...so it's breaking while trying to interpret an empty string from the CSV's inset column as a geometry.

I'm not sure if the CSV is missing an inset, or if this location is referring to the wrong CAP grid.

**Comment by davisagli** [comment]
After yesterday's fix these are not breaking (though they are still unable to determine a location).

**Comment by paregorios** [comment]
I think that getting to non-breaking is good enough on these. They all needed anyway to have something put in place of the raw CAP grid system. So, unless there are any objections from @alecpm or @davisagli , I'm happy to close this ticket.
