### ISSUE TITLE
replace old time-periods vocabulary at /vocabularies with the new one

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#165]
Delete old ATVM-managed time-periods vocabulary and expose the new data-grid one at /vocabularies

**Comment by cguardia** [comment]
One problem that I didn't think of when we discussed this before: right now 'vocabularies' is a folder and it shows all the vocabularies that it contains. We can't get rid of the folder right now, because there's only one registry vocabulary and then the real ones would not show up. For now, we could create a special view for the folder (assigned using the display menu) and add the new registry vocabularies there.

**Comment by paregorios** [comment]
That seems like a reasonable solution.

**Comment by davisagli** [comment]
This is ready for testing on staging.

**Comment by paregorios** [comment]
looks good
