### ISSUE TITLE
locations and names showing up as connections for anonymous viewers

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#173]
Consider [Nora/Col. Norbensis Caesarina](http://pleiades.stoa.org/places/256327).

An admin user, logged in, sees the following, which is what I would expect:

![screen shot 2016-06-28 at 4 11 26 pm](https://cloud.githubusercontent.com/assets/263285/16432531/042e15ac-3d4b-11e6-93b2-0071a5fae04f.png)

But an anonymous user, viewing the same page, sees this:

![screen shot 2016-06-28 at 4 12 20 pm](https://cloud.githubusercontent.com/assets/263285/16432565/24e5d8c0-3d4b-11e6-86dc-33818ace6c75.png)

Why are anonymous users seeing the names and locations that are contained by the place repeated under the "Has a connection with" heading?

**Comment by davisagli** [comment]
I'm pretty sure this is not new--it's a bug in code that we haven't touched. It's a long-standing Plone bug/quirk that you just noticed. It's an edge case in how we are displaying the connections using Plone's folder listing template, but overriding the list of items to display to use the backreferences. The bug is that if the template receives an empty list, it falls back to the normal source of the list (a full folder listing).

It's pretty easy to fix, but is it worth it given the changes we have pending to store and display connections a different way?

**Comment by paregorios** [comment]
@davisagli given the origin as you describe, I agree this is not worth addressing given pending changes. Closing "won't fix".

**Comment by davisagli** [comment]
Well, we "will fix" but without extra effort required. :)
