### ISSUE TITLE
Pending/drafting data output in dumps

### ISSUE THREAD

**Issue by ryanfb** [isawnyu/pleiades-gazetteer#176]
In both the CSV & JSON dumps, I see data that shows as pending/drafting when I log in to the site (and doesn't appear when not logged in).

An example is: http://pleiades.stoa.org/places/659885

In the dumps I see the locations "Undetermined location" (drafting) and "OSM location" (pending) as well as the name "Cendere Köprüsü" (pending).

Potentially related to #7.

**Comment by davisagli** [comment]
I think what we want is:
- Only include published locations, names, and connections in the sitewide dumps
- But if you click the JSON link while logged in viewing a place, include the same ones that you see in the html (i.e. include pending/drafting items that you have permission to view). These are identifiable in the json via the `review_state` key.

@ryanfb @paregorios Sound right?

**Comment by paregorios** [comment]
@davisagli yes exactly

**Comment by davisagli** [comment]
I fixed this on staging and re-ran the dump so you can take a look. Note that the dump has a lot fewer places, which I think is because it ran out of memory and got killed in the middle. That shouldn't be an issue on production (it has a lot more RAM) so the main thing to check is that it's no longer including draft/pending locations, names, and places.

**Comment by paregorios** [comment]
OK, please deploy to production.

**Comment by davisagli** [comment]
Deployed; should take effect for tonight's dump.

**Comment by ryanfb** [comment]
Confirmed that for the latest CSV/JSON dumps, http://pleiades.stoa.org/places/659885 no longer shows drafting/pending data.

**Comment by paregorios** [comment]
Thanks @ryanfb! Closing as resolved.
