### ISSUE TITLE
new-style connections not showing up in place maps

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#178]
On staging, where the new-style connection code has been deployed and the migration steps run, the place map for Sicilia only shows green icons for a fraction of the 200+ connected places that appear in the "Has a connection with" listing:

![screen shot 2016-07-05 at 8 50 35 am](https://cloud.githubusercontent.com/assets/263285/16586868/98d3b396-428d-11e6-8004-6c577fe069c6.png)

This, from production where the old-style connections are still in charge, is what I would expect to see:

![screen shot 2016-07-05 at 9 00 34 am](https://cloud.githubusercontent.com/assets/263285/16587191/0c9c25be-428f-11e6-8a4e-4db5a5f726db.png)

**Comment by paregorios** [comment]
In addition (and I think this is likely a knock-on effect), the representative point is demonstrably the centroid only of those locations shown on the map, not of the whole corpus of the connections:

![screen shot 2016-07-05 at 8 57 15 am](https://cloud.githubusercontent.com/assets/263285/16587064/804e7f62-428e-11e6-877b-490c62b0e0d5.png)

**Comment by davisagli** [comment]
These are similar but un-connected (no pun intended) issues.

The connections are missing from the map because it's based on the @@connections-json view, which needs to be updated to look for the new connections. (This raises the question of why some connections remain on the map. We should check to make sure this doesn't mean the migration left some old references behind.)

The centroid is wrong because the representative point calculation in pleiades.geographer also needs to be updated to look for connections the new way.

This makes me think we haven't done a thorough look for code using the old way of looking up references, so even after fixing the above we should do that before declaring ourselves ready to deploy.

**Comment by cguardia** [comment]
One problem here appears to be that the staging migration was run before changing the getConnections calls in places like pleiades.json and pleaides.rdf. 

I did do a search for all getConnections calls (and getConnections_from too). Is there any other way to query the connections that I might have missed?

**Comment by cguardia** [comment]
Also, the problem with the remaining connections on the map might just be with the reindexing. I changed the script to reindex after all the changes, but maybe the first run before that change resulted in some catalog entries not being updated. I can take a look at that today.

**Comment by davisagli** [comment]
I've fixed the problem with calculating the centroid in pleiades.geographer. (I reindexed Sicilia; it may not be correct again for other places until they are reindexed.) Carlos, it was using .getRefs('connectsWith') rather than .getConnections() so I guess that's why you missed it.

**Comment by davisagli** [comment]
And now the connections missing from the map are fixed too.
