### ISSUE TITLE
HTML title on Pleiades credits page is wrong

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#199]
Here's what we have now:

```
<title property="dcterms:title og:title schema:name">Pleiades: a Pleiades Plone Site resource</title>
```

It should read instead something like:

```
<title property="dcterms:title og:title schema:name">Credits for the Pleiades gazetteer</title>
```

**Comment by witekdev** [comment]
@paregorios 
So it looks like this is due to the fact that the credits page is just a Page Template in the root of the site:
http://pleiades.stoa.org/credits2/pt_editForm
and our rich metadata viewlet calculates the formatted title from the title and content type from the context, and the context is the plone site root. This is also the case for the home page.

These are the formatted titles for each of the top level navigation items:
Home - **"Pleiades: a Pleiades Plone Site resource"**
Browse Places - "Ancient Places in Pleiades: a Pleiades Page resource"
Download Data - "Data for download: a Pleiades Page resource"
Blog - "Pleiades Project Blog: a Pleiades Collection (old-style) resource"
Credits - **"Pleiades: a Pleiades Plone Site resource"**
Vocabs - "Vocabularies: a Pleiades Folder resource"
Documentation - "Documents: a Pleiades Page resource"

The non-bold ones are all ATFolders
eg: http://pleiades.stoa.org/docs/manage_main
(except /places which is a PlaceContainer, but that is still a container type)

**Comment by witekdev** [comment]
Maybe the others (@davisagli @alecpm) can weight in here but perhaps one solution is to manually place the rich metadata code in the these two templates (and customize it for each template) and disable the rich metadata viewlet for the ISiteRoot context?

**Comment by davisagli** [comment]
The easiest solution is to add a folder with an id of `credits` and make its default layout be the credits template. Then we can give whatever title we want to the folder. You will need to rename the credits template so that Plone can traverse to the template rather than just finding the folder via acquisition (or turn it into a browser view so you can reference `@@credits`).

**Comment by witekdev** [comment]
This is still work in progress, my process:

I initially tried to create a Folder (not an ATFolder) with 'credits' as its id, title as 'Credits for the Pleiades gazetteer' and set its layout property by following this process:
http://stackoverflow.com/questions/8914479/how-to-define-default-views-in-plone
(I copied the the credits2 template into the folder and set it as the default layout.)

That did not work, the template was not being found when navigating to the Credits page.
I tried calling the template both 'credits2' or renaming it to 'credits' and updating the default layout appropriately. No go.

I then tried again: Creating a Folder in the root, this time checking the `Create public interface` option:

![screenshot from 2016-08-09 09 52 09](https://cloud.githubusercontent.com/assets/883619/17520979/37ff523c-5e17-11e6-8c68-6f653a68bb1a.png)

I once again proceeded to move the credits2.pt template into this folder, renaming it to 
and overriding the index_html template which the folder had configured as its default view.

That worked but then inside of this credits2/index_html template there is a call to `here/getCredits`
which cannot be resolved in the context of this new credits folder.
(If I comment out this part of the code, this partial template then renders without issues)

I am not sure where that getCredits method sits as grepping for it from parts/omelette did not yield any results. (I grepped with -R which follows symlinks)

Additionally with this half-commented out template working, I then found is that the
Products.PleiadesEntity.browser.credits.formatted_title method still returns the incorrect result from the context of this folder:

```
(Pdb) self.context
<Folder at /plone/credits>
(Pdb) self.context.Title()
'Pleiades'
(Pdb) self.context.Type()
'Plone Site'
(Pdb)
```

so that does not help us solve the original issue that this ticket describes.
I suspect that this might be because I'm using a Folder and not an ATFolder, so those self.context.Title() and self.context.Type() are not returning the correct result for a Folder type?

When attempting to create an ATFolder:

![screenshot from 2016-08-09 10 11 10](https://cloud.githubusercontent.com/assets/883619/17521656/b62611e4-5e19-11e6-8470-d15509ccd420.png)

I get:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 72, in mapply
  Module ZPublisher.Publish, line 53, in missing_name
  Module ZPublisher.HTTPResponse, line 741, in badRequestError
BadRequest:   <h2>Site Error</h2>
  <p>An error was encountered while publishing this resource.
  </p>
  <p><strong>Invalid request</strong></p>

  The parameter, <em>type</em>, was omitted from the request.<p>Make sure to specify all required parameters, and try the request again.</p>
  <hr noshade="noshade"/>

  <p>Troubleshooting Suggestions</p>

  <ul>
  <li>The URL may be incorrect.</li>
  <li>The parameters passed to this resource may be incorrect.</li>
  <li>A resource that this resource relies on may be
      encountering an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>
```

I can create an  `ATPortalTypeCriterion` without issues but I don't think that is what we want?

**Comment by witekdev** [comment]
Maybe the add `ATFolder` functionality is broken since it appears 2x in the drop down and both options take me to the add `ATPortalTypeCriterion` page?

![screenshot from 2016-08-09 10 28 56](https://cloud.githubusercontent.com/assets/883619/17522355/4d70b32c-5e1c-11e6-9379-4dad4ff2ffaa.png)

**Comment by davisagli** [comment]
Add a normal Plone folder via the Plone UI. A plain Zope folder does not have support for default views, and adding Plone content types via the ZMI is not expected to work.

**Comment by witekdev** [comment]
thanks @davisagli that helps a lot, with this new Folder pointing at the plone/credits2 template the Products.PleiadesEntity.browser.credits.formatted_title now correctly detects the Folder type and its title.

however, I still have an issue with the getCredits call:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.PageTemplates.ZopePageTemplate, line 338, in _exec
  Module Products.PageTemplates.ZopePageTemplate, line 435, in pt_render
  Module Products.PageTemplates.PageTemplate, line 87, in pt_render
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 819, in do_loop_tal
  Module zope.tales.tales, line 682, in setRepeat
  Module zope.tales.tales, line 696, in evaluate
   - URL: /plone/credits2
   - Line 57, Column 0
   - Expression: <PathExpr standard:u'here/getCredits'>
   - Names:
      {'container': <PloneSite at /plone>,
       'context': <ATFolder at /plone/credits>,
       'default': <object object at 0x7f02a67cc4f0>,
       'here': <ATFolder at /plone/credits>,
       'loop': {},
       'nothing': None,
       'options': {'args': ()},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f029104ee10>,
       'request': <HTTPRequest, URL=http://localhost:9080/plone/credits/credits2>,
       'root': <Application at >,
       'template': <ZopePageTemplate at /plone/credits2 used for /plone/credits>,
       'traverse_subpath': [],
       'user': <PropertiedUser 'admin'>}
  Module zope.tales.expressions, line 217, in __call__
  Module Products.PageTemplates.Expressions, line 147, in _eval
  Module zope.tales.expressions, line 124, in _eval
  Module Products.PageTemplates.Expressions, line 74, in boboAwareZopeTraverse
  Module OFS.Traversable, line 317, in restrictedTraverse
  Module OFS.Traversable, line 285, in unrestrictedTraverse
   - __traceback_info__: ([], 'getCredits')
AttributeError: getCredits
```

I did not move the template out of the site root.

**Comment by davisagli** [comment]
You must have an old copy of the template; the one we're currently using does not use getCredits: https://github.com/isawnyu/pleiades-notredame/blob/master/pleiades/notredame/skins/pleiades_notredame_custom_templates/credits.pt

**Comment by witekdev** [comment]
@davisagli yeah, I just realised that too. thanks!

**Comment by witekdev** [comment]
@davisagli The problem is that the 'credits' template in use did not show up in the ZMI listing and only the credits2 was there. This is also the case on staging. However credits2 is not present on production I see now.

**Comment by davisagli** [comment]
The `credits` template is in portal_skins, no? I thought credits2 was just something you added?

**Comment by witekdev** [comment]
yes credits is in plone/portal_skins/pleiades_notredame_custom_templates/manage_main
but the credits2 template sits in the root and so that is what I focused on as I thought that is what I needed to display. I did not add it, no. Its last modified timestamp is 2013-02-11 17:26

**Comment by davisagli** [comment]
Okay, please delete the existing credits2 and add your own in the same location as the one we're using from pleiades.notredame.

**Comment by paregorios** [comment]
credits2 is afaik derelict junk

## 

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by witekdev** [comment]
@paregorios on staging

for reference: 
I nuked the credits2 template. I created a credits folder and inside created a credits_template where I copied the contents of plone/portal_skins/pleiades_notredame_custom_templates/ and set that as the layout. I updated the code in the rich metadata viewlet to check if we are dealing with a credits page and if so to only display its title (as opposed to title + content type)

**Comment by davisagli** [comment]
@witekdev maybe we should avoid showing the content type any time it is Folder, not just for the credits page

**Comment by witekdev** [comment]
@davisagli I will wait for @paregorios to comment on that.
also if you want @paregorios for us to add any extra special checks for the other main nav pages?

Copying from earlier comment:
These are the formatted titles for each of the top level navigation items:

```
Home - "Pleiades: a Pleiades Plone Site resource"
Browse Places - "Ancient Places in Pleiades: a Pleiades Page resource"
Download Data - "Data for download: a Pleiades Page resource"
Blog - "Pleiades Project Blog: a Pleiades Collection (old-style) resource"
Credits - FIXED
Vocabs - "Vocabularies: a Pleiades Folder resource"
Documentation - "Documents: a Pleiades Page resource"
```

**Comment by paregorios** [comment]
@witekdev and @davisagli thanks for thinking about these particular cases. I think I would like to step back to address only certain types of content. 

Here are the types for which I would like to continue seeing the "{title}: A Pleiades {contentype} resource" pattern:
- place
- name
- location
- connection

All other types should just use the pattern "{title}" I think.

Is that possible?

**Comment by witekdev** [comment]
@paregorios yes, I think it should be fairly easy to make the modifications..

**Comment by paregorios** [comment]
Great! Let's do that please.

## 

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by witekdev** [comment]
on staging

**Comment by witekdev** [comment]
@paregorios and I took the liberty of releasing it to production.

**Comment by paregorios** [comment]
And it looks good. Thanks.

**Comment by paregorios** [comment]
@davisagli and/or @witekdev : sorry to bug you, but am I right in reading [the comment above](https://github.com/isawnyu/pleiades-gazetteer/issues/199#issuecomment-238682807) to mean that [pleiades-notredame/.../credits.pt](https://github.com/isawnyu/pleiades-notredame/blob/master/pleiades/notredame/skins/pleiades_notredame_custom_templates/credits.pt) is now ignored and instead if I want to change its content I need to edit ```plone/credits/credit_template``` via the ZMI?

**Comment by davisagli** [comment]
Yeah that looks correct.

**Comment by paregorios** [comment]
Thanks
