### ISSUE TITLE
Get credits page (and other pages) under version control

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#20]
Productize these pages ASAP. This is a precarious position to be in.

Migrated from http://pleiades.stoa.org/docs/site-issue-tracker/20, where it was originally opened by @sgillies.

**Comment by paregorios** [comment]
Here are a few questions for @davisagli and/or @alecpm regarding the P4 staging version of the code: 

- What page-like components of the site are outside the plone? Are any of them not under version control? 
- IIRC, /credits was a custom template managed through the ZMI. Is this still the case? Should we move to something more code-like?
- Can/should these issues be pushed after the initial P4 deployment to production?
- Are there other related/similar issues we should address ahead of the initial P4 deployment to production?

**Comment by davisagli** [comment]
I made sure that all changes in the custom folder, including the credits template, are copied into a filesystem skin layer in pleiades.notredame so that we can clear out the custom folder after we upgrade.

In the long run credits should probably be a modern browser view, but there's no pressing reason to put time into that unless we're making other changes to it.

I'm not sure about pages outside of Plone. Alec probably has a better sense of that from looking at the apache configuration.

**Comment by paregorios** [comment]
Will wait to see if @alecpm has anything to add before clearing and closing this issue.

**Comment by paregorios** [comment]
I'm under the impression that this is not essential before deploying the P4 upgrade; however, there is the open question of non-ploneish components on the server, on which I'll need to confer more closely with @alecpm

**Comment by paregorios** [comment]
I think this can be closed, yes?
