### ISSUE TITLE
pleiades dumps (csv, json, possibly others) are erroring off incomplete

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#206]
Last full set seems to date to 3 August. Daily there seem to be detritus of failed runs.

**Comment by alecpm** [comment]
There seem to have been a couple issues here. First the pleiades-dump-all script was erroring out due to a permission issue in the dump code, so new dumps were not being created for either csv or json. Additionally, the pleiades-json dump script was still running nightly, and that was replicating the dumps, but without rotation or compression. I have disabled that redundant script.

Things appear to be running smoothly now. Unfortunately, when the dump script ran successfully it deleted all dumps older than 7 days (as it is supposed to), which means that – for now – only the most recent dump is available.

**Comment by paregorios** [comment]
everything checks good.
