### ISSUE TITLE
Connected place does not show that it is in drafting/pending state

### ISSUE THREAD

**Issue by atomrab** [isawnyu/pleiades-gazetteer#228]
When viewing https://pleiades.stoa.org/places/865014139 while not logged in, I can see that it has a connection with Lucus Stimulae, which appears as a normally-colored live link (below).

![image](https://cloud.githubusercontent.com/assets/4740995/19003228/88d241f2-8715-11e6-97e3-b8e4a245e754.png)

If I follow that link, however, I'm taken to a login page, and if I log in, I discover that this place is actually pending (https://pleiades.stoa.org/places/978725164). 

If I'm a user without permission to see that place, I would like to have some way to tell that it's not available for viewing/not published (all the more critical now that a lot of things that would have been drafting locations are now drafting places, and so will only show up as connections). If possible, it would be useful to represent the link as "Lucus Stimulae (pending review)" or "Lucus Stimulae (drafting)". Using the color conventions for draft and review-state items might also help.

**Comment by paregorios** [comment]
[Enhancements made last year to the connections listings in places pages](https://github.com/isawnyu/PleiadesEntity/pull/34) addressed this concern,  but I failed to connect back to this ticket. Here's what one sees now:

![Screen Shot 2019-03-22 at 1 09 56 PM](https://user-images.githubusercontent.com/263285/54844054-e6f97880-4ca3-11e9-8ba1-55f025bb7c54.png)

@atomrab if you concur that this concern is now addressed, please close this ticket. Otherwise please comment as to suggested next steps.
