### ISSUE TITLE
KMZ dump still has busted icons

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#240]
It looks like we didn't catch this when we were fixing #220.

**Comment by witekdev** [comment]
@paregorios How can I reproduce this?

**Comment by paregorios** [comment]
@witekdev Download pleiades-latest.kmz from http://atlantides.org/downloads/pleiades/kml/ and open it in Google Earth.

**Comment by witekdev** [comment]
From what I can see:
If the place contains a single location, it has an icon. Otherwise if it contains more than one location, on the google map it is indicated as a line or triangle etc connecting the locations, it does not have an icon in that case. @paregorios is this what you were referring to? I did not see occurrences of missing icons in the way that we had with https://github.com/isawnyu/pleiades-gazetteer/issues/220

eg. El Faro (2 locations)
![untitled-2](https://cloud.githubusercontent.com/assets/883619/20574829/5605a388-b16b-11e6-8049-ea706fa37e50.jpg)
![untitled-3](https://cloud.githubusercontent.com/assets/883619/20574830/560a96fe-b16b-11e6-9aca-39d5ed6e5f53.jpg)

Satricum (3 locations)
![untitled-4](https://cloud.githubusercontent.com/assets/883619/20574842/634fcea6-b16b-11e6-991a-f85c006b75c0.jpg)
![untitled-5](https://cloud.githubusercontent.com/assets/883619/20574843/6350632a-b16b-11e6-85a0-6893e27a0c2a.jpg)

**Comment by paregorios** [comment]
No, I'm talking about the single KMZ dump of everything, in which
non-polygon features display like this for me in google earth:

​

## 

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by witekdev** [comment]
@paregorios looks like the image didn't come through?

**Comment by paregorios** [comment]
sorry, guess it didn't cross post from email: 

![yuck](https://cloud.githubusercontent.com/assets/263285/20575147/abdc470a-b17d-11e6-9c00-b2dbf57fb293.jpg)

**Comment by witekdev** [comment]
@paregorios that is strange as I'm seeing this for the same region:
![untitled-6](https://cloud.githubusercontent.com/assets/883619/20575245/52755f86-b16d-11e6-9f8d-9062de82fbbc.jpg)

**Comment by witekdev** [comment]
This is coming out of ```	pleiades-latest.kmz	2016-11-23 07:43	1.8M	 ```

**Comment by witekdev** [comment]
```
Google Earth Pro
7.1.7.2606
Build Date
10/6/2016
Build Time
1:52:36 pm
Renderer
DirectX
Operating System
Microsoft Windows (6.1.7601.1)
```

**Comment by paregorios** [comment]
Closing this issue as being entirely confined to the space between this user's computer and his chair. Sorry for the noise.

**Comment by witekdev** [comment]
Pebkac :)
