### ISSUE TITLE
update front page to use Mapbox GL JS v1.0.0 or higher for map

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#405]
We want to move to [the new mapbox pricing per map load](https://www.mapbox.com/pricing/#maploads) (we currently pay by the raster tile hit), but to do this we need to be using "Mapbox GL JS v1.0.0 and above". There's a deadline of November 20, 2019 to make this change or unattractive pricing effects kick in.

As of today, the current version of [Mapbox GL JS](https://docs.mapbox.com/mapbox-gl-js/api/) is 1.2.1. The first thing we need to do, I think, is determine whether this is a straightforward swap-in for what we're using now, or (worse) if we have to rewrite our in-browser map code, or (even worser) we have to reconfigure/remake components on the Mapbox server side.

**Comment by paregorios** [comment]
This is a blocker for #361, #406, #407, #408, and #409

**Comment by paregorios** [comment]
I don't think we can properly estimate this ticket until we know whether this is a swap-in or worse as outlined in my comment above. @skleinfeldt does it make sense to assign this to @MatthewWilkes for the purpose of conducting that assessment?

**Comment by skleinfeldt** [comment]
With this blocking so many things (and #351 deemed lower priority), I think it does make sense to have @MatthewWilkes work on this first.

**Comment by paregorios** [comment]
Thanks @skleinfeldt. I have assigned it to @MatthewWilkes accordingly.

**Comment by MatthewWilkes** [comment]
I believe this is the "worse" state. I don't think we need to rework any mapbox serverside components, however it appears to me that parts of the map integration will have to be re-written. Every option I've checked so far appears to be present in the new version, however the syntax is rather different.

**Comment by MatthewWilkes** [comment]
I've updated the front page and deployed it to staging. This is now using the mapbox gl style. The biggest visual difference is the attribution is no longer hidden behind an i circle. You may need to clear cache or force refresh to see it load.

I tried to approximate the same visual behaviour as the old map, but there was a change to the way zooming worked. They have chosen a new zoom system that they think people find more pleasing, and it does seem nice. I tried to match the time to zoom instead of the exact zoom behaviour. I also changed the timings for display of the marker and popup so they don't disappear until just before panning starts (previously they disappeared as soon as the site started looking for a new place to show, which could take a while). I also made the marker appear immediately in the new location before panning starts, but kept the popup only appearing once panning finishes. This looks better to my eyes, with the changes in zoom behaviour.

**Comment by paregorios** [comment]
This looks good. Please merge to master and deploy to production.

**Comment by MatthewWilkes** [comment]
On production

**Comment by paregorios** [comment]
This looks great!
