### ISSUE TITLE
roles misbehavior

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#450]

**Comment by alecpm** [comment]
So it turns out this is one I've seen before and it has to do with a missing `data-` attribute on the body tag that Plone expects to be present in order to determine the base url to use for certain AJAX requests. I'm surprised to be seeing this on a Plone 4 site, but it's almost certainly just a small tweak to the Diazo rules file to pull in the body tag data attributes.

**Comment by alecpm** [comment]
Looks like it was the custom main_template that needed the additional `data-` attributes since pleiades.notredame is not a Diazo theme, but it was a simple fix nonetheless. I've made the updates removes the undesirable role assignments.
