### ISSUE TITLE
newly created locations often do not show up on parent place map in a timely manner: 5pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#465]
This bug is a significant impediment to content creation, editing, and review. 

Newly created locations **do** show up immediately on the map in the location view, but they do not always show up immediately on the parent place view. They do seem to **eventually** show up, but user experience indicates that the delay is somewhere between several hours and as much as several weeks. Sometimes they show up right away, especially (only?) when another draft or pending location added earlier is already showing up in the map. 

For example, an appropriately authenticated user (reviewer/admin) will see a pending OSM location on the map on [the Oeroe (river) place page](https://pleiades.stoa.org/places/540967) but not, at the time of this writing, on the [Ad Decimum working copy place page](https://pleiades.stoa.org/places/copy_of_314848). 

## Steps to recreate (which have been followed on this test place: https://pleiades.stoa.org/places/868552020
- create a new place
- import a location from an OSM node
- note that the point DOES show up on the location view map
- save the location
- navigate back to the place
- note that the point DOES NOT show up on the place map view
- refreshing makes no difference
- ssh into the host, restart varnish, refresh in browser: no change
- open a completely different browser, login to pleiades, navigate to the place page: NO DIFFERENCE

**Comment by paregorios** [comment]
I suspect that this problem is not occurring in [the map javascript](https://github.com/isawnyu/PleiadesEntity/blob/master/Products/PleiadesEntity/skins/PleiadesEntity/place_map.js), but rather has something to do with the location data consumed by the map javascript, which is packaged for consumption by code running somewhere in the plone.

**Comment by jessesnyder** [comment]
If not reproducible, ask @paregorios for help with this.

**Comment by alecpm** [comment]
I think there are a couple of potential issues at play here.

One is aggressive caching of the JSON APIs on the Plone side, in particular aggressive caching headers for varnish, as well as a RAMCache. Another is additional caching headers set in apache that tells browsers to cache all JSON content for a day. I've updated the caching to be more reasonable in both Plone and varnish, only proxy caching content for non-logged in users and doing so less aggressively. I think the site could benefit from some additional cache purging customizations so that edits to places/locations result in the cached anonymous JSON representations getting purged automatically.

Another is that the `bbox` value of a place does not ever incorporate non-public locations, so a place with only non-published locations will have a `null` bounding box. That choice seems to be quite explicit here:

https://github.com/isawnyu/pleiades-geographer/blob/master/pleiades/geographer/catalog.py#L80

Unfortunately, a `null` bbox for the location results in a JS error in [early on in the map code](https://github.com/isawnyu/PleiadesEntity/blob/bd7c2ee2629657f2ce3ac8e1d52ef5af0e412cac/Products/PleiadesEntity/skins/PleiadesEntity/place_map.js#L175-L176), which prevents it from rendering any of the locations contained in the JSON. I think we can make a small fix to the JS to ignore a null bbox value and instead calculate a zoom to fit all locations visible in the JSON.

**Comment by alecpm** [comment]
@paregorios The changed caching settings appear to have resolved the issue on staging when there's already at least one published location:

http://pleiades.jazkarta.com/places/868552020/

Note that because the `bbox` is based on only the published location, the initial zoom level is initially too tight to see the second location. Maybe we should always set the zoom level based on the plotted locations rather than using the API `bbox` value, which only incorporates published locations?

**Comment by paregorios** [comment]
@alecpm agree that we should set the zoom level based on the plotted locations, rather than API `bbox`.

**Comment by paregorios** [comment]
FWIW I think aggressive caching of the JSON resources both server-side and client-side was aimed at anonymous users, especially bots that don't behave politely (but also refresh-and-multi-tab-happy users).

**Comment by alecpm** [comment]
The caching for anon-users and bots should essentially remain the same. The exception would be for the client side caching change, which might cause refresh happy users to fetch from the varnish cache more often, but not impact bots.

**Comment by alecpm** [comment]
Deceased users seem to have an `email` address set to a value like `deceased nov 2003`. I propose we look for `deceased ` in the email and if we find it set the email to `testing@cmc.org` so there's a valid email, set the `deceased` flag to `True`, and set the username to use the default means of constructing it (first-last).

**Comment by alecpm** [comment]
@paregorios This seems to be working well on staging now. See http://pleiades.jazkarta.com/places/868552020 for an example. So far adding, publishing, retracting, etc. locations all seem to result in immediate changes to the map on reload. You may need to clear your browser cache to get the latest map JS.

Once approved, I'll make the caching updates and production and also push the JS changes to ensure the map renders properly even when it has no public locations and always zooms to a level that includes all rendered locations.

**Comment by paregorios** [comment]
This seems to be working perfectly on staging.

**Comment by alecpm** [comment]
This is deployed. Because we've reduced RAM caching and some proxy/browser caching of API resources we should keep an eye on how CPU performance changes over the next couple of days. I don't expect any problems, but it would be good to know if there's a noticeable impact.

**Comment by paregorios** [comment]
This is working perfectly on production. I will close this ticket when I have the requested CPU performance monitoring and alerts in place.

**Comment by paregorios** [comment]
So far, no wild, out-of-band CPU increases, but possibly a bit higher in band over the last 24hours. We'll know more when we have a week's series of data since the change:

![cpu](https://user-images.githubusercontent.com/263285/160129239-354e6c3d-4c79-493b-95c7-c5aadbc31d52.jpg)

**Comment by skleinfeldt** [comment]
Are the spikes because of crawlers, or the nightly data dumps, or something else? Just curious...

**Comment by paregorios** [comment]
Data dumps. Someday it might be worth looking at rolling these off to some
kind of spot instance and downsizing the main host.

On Fri, Mar 25, 2022 at 8:48 AM Sally Kleinfeldt ***@***.***>
wrote:

> Are the spikes because of crawlers, or the nightly data dumps, or
> something else? Just curious...
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_isawnyu_pleiades-2Dgazetteer_issues_465-23issuecomment-2D1079046045&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7JN6srnWbiUKKqSduQp_AZyX8Y6wZvZSbFNLOC4QkwA&m=v6yPjCeQ3ZMFVGHd-e7BC2qdeC4tOWxaLmmdde4pNI2TMAsEfbvfh6TxYDPS5xsg&s=cM3MjdNJLifJ4aS70oWp9boSyON-HdLY6AvLB283xZM&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AACAI5IUQGTUS47NJLL5WFLVBW72XANCNFSM5NUAZE4Q&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7JN6srnWbiUKKqSduQp_AZyX8Y6wZvZSbFNLOC4QkwA&m=v6yPjCeQ3ZMFVGHd-e7BC2qdeC4tOWxaLmmdde4pNI2TMAsEfbvfh6TxYDPS5xsg&s=pprmY6vm2yv6CWGo9gtr7AaBxxe3SkH9I3yC9SuT5iE&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>
-- 
-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

pronouns: he, him
https://paregorios.org/
Humanities Commons: @paregorios <https://hcommons.org/members/paregorios/>
OrcID: 0000-0002-4114-6677 <http://orcid.org/0000-0002-4114-6677>

**Comment by paregorios** [comment]
I propose we go ahead and close this ticket. If we do have CPU issues, those will show up in the course of regular monitoring and we can address with a new issue from there. Sound ok @alecpm ?

**Comment by alecpm** [comment]
@paregorios sounds good.
