### ISSUE TITLE
default text for content "submit" action - 5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#76]
As an authenticated pleiades user preparing to submit a piece of content for review, I am currently presented with an empty "comments" field on the "Publishing Process" page:

![Screen Shot 2019-03-25 at 10 14 08 AM](https://user-images.githubusercontent.com/263285/54931336-cd943e80-4ee6-11e9-999d-197dbb75ed59.png)

Instead, I would like to see the comments box pre-populated with any and all iterate save messages made since the last "publish" state transition (if there ever was one). These should be concatenated with semicolon+space as delimiter. If there are subordinate content items getting submitted at the same time, add text like this as appropriate: "updated {contained object type names}".

I will be able to modify this text prior to submitting the content item for publication.

**Comment by paregorios** [comment]
See also issues nos. #365 and #366

**Comment by alecpm** [comment]
Should the commit messages be ordered oldest first, or newest first?

**Comment by paregorios** [comment]
oldest first please

**Comment by alecpm** [comment]
I've got a first pass of this up on staging. When the `content_status_history` form is loaded with the `workflow_action` set to `submit` it should include all revision comments for the item since the item's last `publish` transition. Additionally, any if any sub-objects were modified since the last `publish` transition an additional comment will be added in the form `; updated Connections, Names`.

I'm not quite sure this is sufficient, since on my local instance it's not quite clear to me how someone would get to the workflow form for an item with the `submit` action pre-selected.

**Comment by paregorios** [comment]
This is working the way I hoped it would on staging. Unless there's a wrinkle you're seeing that I don't, please merge to master and deploy to production.

**Comment by alecpm** [comment]
This is merged and deployed.
