### ISSUE TITLE
place history compare fails with AttributeError

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#95]
This is occurring on P4 staging, not on production.

As a logged-in, admin user:

- Visit ```/places/433211/@@historyview```
- Select any ```↑ Compare ↓``` link
- See something like this:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFEditions.browser.diff, line 58, in __call__
  Module Products.CMFDiffTool.CMFDiffTool, line 156, in createChangeSet
  Module Products.CMFDiffTool.ChangeSet, line 83, in computeDiff
  Module Products.CMFDiffTool.CMFDiffTool, line 142, in computeDiff
  Module Products.CMFDiffTool.namedfile, line 103, in __init__
AttributeError: 'str' object has no attribute 'data'
```

**Comment by davisagli** [comment]
The place content type's diff settings had been customized so that it explicitly uses a `List Diff` for the `placeType` field, rather than the defaults. This was triggering a Plone bug because it appears that the List Diff registration has been accidentally overridden by a differ that expects files.

I fixed the `placeType` field to be correctly declared as a LinesField (it was previously declared as a StringField but actually storing a list), and reset the diff settings to the default.

I'll add this to the launch checklist so I remember to do it again when we launch.

It appears that CMFDiffTool does not handle showing an inline diff for lines fields, but only a code diff. I've submitted an upstream improvement to show an inline diff, and can update to that once it's accepted into Plone core.

**Comment by paregorios** [comment]
Staging seems to be responding very slowly this morning, so I am not able to verify.

**Comment by paregorios** [comment]
In fact I'm getting 503s.

**Comment by alecpm** [comment]
My fault, I started the RDF export, which seems to consume all resources (even when run with ``nice -n 19``).  My guess is it's exhausting RAM (though that would normally trigger an OOM kill on the exporter). Rebooting now.

**Comment by davisagli** [comment]
Back up now. From syslog it looks like the instances became inaccessible at 7:28 and a python process was OOM-killed at 7:50

**Comment by alecpm** [comment]
It stayed inaccessible for a while after the OOM kill and the reboot went through at 11:20. Looks like we should probably look into optimizing RAM usage during the RDF export.

**Comment by davisagli** [comment]
Let's keep this open until I get that Plone fix added.

**Comment by davisagli** [comment]
The fix to CMFDiffTool is now in place. If you edit a place and change the place type, then compare the versions, you should see an inline diff for the place type.
