### ISSUE TITLE
dashboard and full review lists are slow to load

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#97]
I.e., ```/dashboard``` and ```/full_review_list```.

For authenticated users with editorial privileges (i.e., can see "pending" items). A significant factor, of course, is that we have over 1,500 items in pending state. Is there anything that can be done to speed this up?

**Comment by davisagli** [comment]
Well, we should certainly limit how many are shown in the Review List portlet. Should we show the oldest or most recently modified items pending review?

As for the full review list, it looks like Plone builds it in an inefficient way that loads full objects rather than using catalog results. So we could probably rewrite that and make it work much better.

I'm guessing reviewers are not going to scroll through pages and pages of items though. Is there any factor by which we can narrow the list down to the ones that a reviewer is actually interested in? Or do we need a way to "assign" items to a particular reviewer (either automatically or manually) so they can see their personal todo list?

**Comment by paregorios** [comment]
For the review list portlet, is it easy to limit it to the n most recent items?

For the full review list, this is sounding more like a enhancement/feature request. Should we defer that aspect to a future milestone? The editors are currently in the habit of using advanced search to filter items in pending state.

**Comment by davisagli** [comment]
#98 is also related to enhancing the full review list.

**Comment by davisagli** [comment]
It's not completely trivial to show the most recent n items in the review list, because we need to change how the list is looked up from the workflow tool to avoid fetching the entire thing. But can probably be done in an hour or two.

**Comment by paregorios** [comment]
I think that would be worth doing.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by cguardia** [comment]
I changed the portlet to show only the 20 most recent items. Is that number OK or should I change it?

**Comment by paregorios** [comment]
20 sounds good thanks

On Thursday, April 7, 2016, Carlos de la Guardia <notifications@github.com>
wrote:

> I changed the portlet to show only the 20 most recent items. Is that
> number OK or should I change it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/isawnyu/pleiades-gazetteer/issues/97#issuecomment-206704125>
>


-- 
-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by cguardia** [comment]
Deployed.

**Comment by paregorios** [comment]
The dashboard now loads much faster thanks to the changes to the portlet. Shall I close this ticket and make a new separate one for the more extensive changes that will be needed to make the full review list faster? I assume from trying it that nothing has yet been done on that score.

**Comment by davisagli** [comment]
That sounds good.

**Comment by paregorios** [comment]
Review list speed enhancements have been hived off as their own issue ticket (#116) and placed on the backlog.
